# Generated by Django 2.2.4 on 2019-08-17 14:06

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190815_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.FileField(null=True, upload_to=crm.models.get_file_path),
        ),
    ]
